const EXERCISE_CATALOG = [
    // Chest
    ["barbell-bench-press", "Barbell Bench Press", "Chest", "Barbell", ["Triceps", "Front Delts"]],
    ["incline-barbell-bench", "Incline Barbell Bench Press", "Upper Chest", "Barbell", ["Triceps", "Front Delts"]],
    ["decline-barbell-bench", "Decline Barbell Bench Press", "Chest", "Barbell", ["Triceps"]],
    ["dumbbell-bench-press", "Dumbbell Bench Press", "Chest", "Dumbbells", ["Triceps", "Front Delts"]],
    ["incline-dumbbell-press", "Incline Dumbbell Press", "Upper Chest", "Dumbbells", ["Triceps", "Front Delts"]],
    ["dumbbell-fly", "Dumbbell Fly", "Chest", "Dumbbells", []],
    ["cable-fly", "Cable Fly", "Chest", "Cable", []],
    ["low-to-high-cable-fly", "Low-to-High Cable Fly", "Upper Chest", "Cable", []],
    ["pec-deck", "Pec Deck", "Chest", "Machine", []],
    ["chest-press-machine", "Chest Press Machine", "Chest", "Machine", ["Triceps"]],
    ["incline-chest-press-machine", "Incline Chest Press Machine", "Upper Chest", "Machine", ["Triceps"]],
    ["push-up", "Push-Up", "Chest", "Bodyweight", ["Triceps", "Front Delts"]],
    ["weighted-push-up", "Weighted Push-Up", "Chest", "Bodyweight", ["Triceps"]],
    ["chest-dip", "Chest Dip", "Chest", "Bodyweight", ["Triceps"]],
    ["landmine-press", "Landmine Press", "Upper Chest", "Landmine", ["Front Delts", "Triceps"]],

    // Back
    ["deadlift", "Conventional Deadlift", "Back", "Barbell", ["Glutes", "Hamstrings", "Traps"]],
    ["sumo-deadlift", "Sumo Deadlift", "Glutes", "Barbell", ["Quads", "Back"]],
    ["barbell-row", "Barbell Row", "Back", "Barbell", ["Biceps", "Rear Delts"]],
    ["pendlay-row", "Pendlay Row", "Back", "Barbell", ["Biceps"]],
    ["dumbbell-row", "One-Arm Dumbbell Row", "Lats", "Dumbbells", ["Biceps"]],
    ["chest-supported-row", "Chest-Supported Row", "Back", "Dumbbells", ["Biceps", "Rear Delts"]],
    ["t-bar-row", "T-Bar Row", "Back", "Machine", ["Biceps"]],
    ["seated-cable-row", "Seated Cable Row", "Back", "Cable", ["Biceps"]],
    ["wide-cable-row", "Wide-Grip Cable Row", "Upper Back", "Cable", ["Rear Delts", "Biceps"]],
    ["lat-pulldown", "Lat Pulldown", "Lats", "Cable", ["Biceps"]],
    ["neutral-pulldown", "Neutral-Grip Lat Pulldown", "Lats", "Cable", ["Biceps"]],
    ["single-arm-pulldown", "Single-Arm Lat Pulldown", "Lats", "Cable", ["Biceps"]],
    ["straight-arm-pulldown", "Straight-Arm Pulldown", "Lats", "Cable", []],
    ["pull-up", "Pull-Up", "Lats", "Bodyweight", ["Biceps"]],
    ["chin-up", "Chin-Up", "Lats", "Bodyweight", ["Biceps"]],
    ["assisted-pull-up", "Assisted Pull-Up", "Lats", "Machine", ["Biceps"]],
    ["machine-high-row", "Machine High Row", "Upper Back", "Machine", ["Biceps"]],
    ["machine-low-row", "Machine Low Row", "Lats", "Machine", ["Biceps"]],
    ["back-extension", "Back Extension", "Lower Back", "Bodyweight", ["Glutes", "Hamstrings"]],
    ["rack-pull", "Rack Pull", "Back", "Barbell", ["Traps", "Glutes"]],

    // Shoulders and traps
    ["overhead-press", "Barbell Overhead Press", "Shoulders", "Barbell", ["Triceps"]],
    ["dumbbell-shoulder-press", "Dumbbell Shoulder Press", "Shoulders", "Dumbbells", ["Triceps"]],
    ["arnold-press", "Arnold Press", "Shoulders", "Dumbbells", ["Triceps"]],
    ["machine-shoulder-press", "Machine Shoulder Press", "Shoulders", "Machine", ["Triceps"]],
    ["dumbbell-lateral-raise", "Dumbbell Lateral Raise", "Side Delts", "Dumbbells", []],
    ["cable-lateral-raise", "Cable Lateral Raise", "Side Delts", "Cable", []],
    ["machine-lateral-raise", "Machine Lateral Raise", "Side Delts", "Machine", []],
    ["front-raise", "Front Raise", "Front Delts", "Dumbbells", []],
    ["reverse-pec-deck", "Reverse Pec Deck", "Rear Delts", "Machine", ["Upper Back"]],
    ["rear-delt-cable-fly", "Rear Delt Cable Fly", "Rear Delts", "Cable", ["Upper Back"]],
    ["face-pull", "Face Pull", "Rear Delts", "Cable", ["Upper Back"]],
    ["barbell-shrug", "Barbell Shrug", "Traps", "Barbell", []],
    ["dumbbell-shrug", "Dumbbell Shrug", "Traps", "Dumbbells", []],
    ["upright-row", "Upright Row", "Shoulders", "Cable", ["Traps"]],

    // Biceps and forearms
    ["barbell-curl", "Barbell Curl", "Biceps", "Barbell", ["Forearms"]],
    ["ez-bar-curl", "EZ-Bar Curl", "Biceps", "EZ Bar", ["Forearms"]],
    ["dumbbell-curl", "Dumbbell Curl", "Biceps", "Dumbbells", ["Forearms"]],
    ["alternating-curl", "Alternating Dumbbell Curl", "Biceps", "Dumbbells", ["Forearms"]],
    ["incline-curl", "Incline Dumbbell Curl", "Biceps", "Dumbbells", []],
    ["preacher-curl", "Preacher Curl", "Biceps", "Machine", []],
    ["cable-curl", "Cable Curl", "Biceps", "Cable", []],
    ["bayesian-curl", "Bayesian Cable Curl", "Biceps", "Cable", []],
    ["hammer-curl", "Hammer Curl", "Biceps", "Dumbbells", ["Forearms"]],
    ["rope-hammer-curl", "Rope Hammer Curl", "Biceps", "Cable", ["Forearms"]],
    ["concentration-curl", "Concentration Curl", "Biceps", "Dumbbells", []],
    ["reverse-curl", "Reverse Curl", "Forearms", "EZ Bar", ["Biceps"]],
    ["wrist-curl", "Wrist Curl", "Forearms", "Dumbbells", []],
    ["wrist-roller", "Wrist Roller", "Forearms", "Other", []],

    // Triceps
    ["close-grip-bench", "Close-Grip Bench Press", "Triceps", "Barbell", ["Chest"]],
    ["tricep-pushdown", "Cable Tricep Pushdown", "Triceps", "Cable", []],
    ["rope-pushdown", "Rope Tricep Pushdown", "Triceps", "Cable", []],
    ["single-arm-pushdown", "Single-Arm Tricep Pushdown", "Triceps", "Cable", []],
    ["reverse-grip-pushdown", "Reverse-Grip Pushdown", "Triceps", "Cable", []],
    ["overhead-cable-extension", "Overhead Cable Tricep Extension", "Triceps", "Cable", []],
    ["dumbbell-overhead-extension", "Dumbbell Overhead Tricep Extension", "Triceps", "Dumbbells", []],
    ["skull-crusher", "EZ-Bar Skull Crusher", "Triceps", "EZ Bar", []],
    ["tricep-dip", "Tricep Dip", "Triceps", "Bodyweight", ["Chest"]],
    ["assisted-dip", "Assisted Dip", "Triceps", "Machine", ["Chest"]],
    ["diamond-push-up", "Diamond Push-Up", "Triceps", "Bodyweight", ["Chest"]],
    ["tricep-kickback", "Tricep Kickback", "Triceps", "Dumbbells", []],

    // Quads, hamstrings and glutes
    ["back-squat", "Barbell Back Squat", "Quads", "Barbell", ["Glutes", "Hamstrings"]],
    ["front-squat", "Front Squat", "Quads", "Barbell", ["Glutes"]],
    ["goblet-squat", "Goblet Squat", "Quads", "Dumbbells", ["Glutes"]],
    ["hack-squat", "Hack Squat", "Quads", "Machine", ["Glutes"]],
    ["smith-squat", "Smith Machine Squat", "Quads", "Smith Machine", ["Glutes"]],
    ["leg-press", "Leg Press", "Quads", "Machine", ["Glutes"]],
    ["single-leg-press", "Single-Leg Press", "Quads", "Machine", ["Glutes"]],
    ["leg-extension", "Leg Extension", "Quads", "Machine", []],
    ["walking-lunge", "Walking Lunge", "Quads", "Dumbbells", ["Glutes"]],
    ["reverse-lunge", "Reverse Lunge", "Glutes", "Dumbbells", ["Quads"]],
    ["bulgarian-split-squat", "Bulgarian Split Squat", "Quads", "Dumbbells", ["Glutes"]],
    ["step-up", "Step-Up", "Quads", "Dumbbells", ["Glutes"]],
    ["romanian-deadlift", "Romanian Deadlift", "Hamstrings", "Barbell", ["Glutes", "Lower Back"]],
    ["dumbbell-rdl", "Dumbbell Romanian Deadlift", "Hamstrings", "Dumbbells", ["Glutes"]],
    ["stiff-leg-deadlift", "Stiff-Leg Deadlift", "Hamstrings", "Barbell", ["Glutes"]],
    ["seated-leg-curl", "Seated Leg Curl", "Hamstrings", "Machine", []],
    ["lying-leg-curl", "Lying Leg Curl", "Hamstrings", "Machine", []],
    ["nordic-curl", "Nordic Hamstring Curl", "Hamstrings", "Bodyweight", []],
    ["good-morning", "Good Morning", "Hamstrings", "Barbell", ["Glutes", "Lower Back"]],
    ["hip-thrust", "Barbell Hip Thrust", "Glutes", "Barbell", ["Hamstrings"]],
    ["glute-bridge", "Glute Bridge", "Glutes", "Bodyweight", ["Hamstrings"]],
    ["cable-kickback", "Cable Glute Kickback", "Glutes", "Cable", []],
    ["hip-abduction", "Hip Abduction Machine", "Glutes", "Machine", []],
    ["hip-adduction", "Hip Adduction Machine", "Adductors", "Machine", []],

    // Calves and core
    ["standing-calf-raise", "Standing Calf Raise", "Calves", "Machine", []],
    ["seated-calf-raise", "Seated Calf Raise", "Calves", "Machine", []],
    ["leg-press-calf-raise", "Leg Press Calf Raise", "Calves", "Machine", []],
    ["single-leg-calf-raise", "Single-Leg Calf Raise", "Calves", "Bodyweight", []],
    ["cable-crunch", "Cable Crunch", "Abs", "Cable", []],
    ["hanging-leg-raise", "Hanging Leg Raise", "Abs", "Bodyweight", ["Hip Flexors"]],
    ["captains-chair-raise", "Captain's Chair Leg Raise", "Abs", "Machine", ["Hip Flexors"]],
    ["ab-wheel", "Ab Wheel Rollout", "Abs", "Other", []],
    ["plank", "Plank", "Core", "Bodyweight", []],
    ["side-plank", "Side Plank", "Obliques", "Bodyweight", ["Core"]],
    ["russian-twist", "Russian Twist", "Obliques", "Bodyweight", ["Abs"]],
    ["pallof-press", "Pallof Press", "Core", "Cable", ["Obliques"]],
    ["woodchop", "Cable Woodchop", "Obliques", "Cable", ["Core"]],
    ["decline-sit-up", "Decline Sit-Up", "Abs", "Bodyweight", []],

    // Olympic, carries and conditioning
    ["power-clean", "Power Clean", "Full Body", "Barbell", ["Glutes", "Traps"]],
    ["hang-clean", "Hang Clean", "Full Body", "Barbell", ["Glutes", "Traps"]],
    ["clean-and-press", "Clean and Press", "Full Body", "Barbell", ["Shoulders"]],
    ["kettlebell-swing", "Kettlebell Swing", "Glutes", "Kettlebell", ["Hamstrings", "Core"]],
    ["farmers-carry", "Farmer's Carry", "Full Body", "Dumbbells", ["Forearms", "Traps", "Core"]],
    ["sled-push", "Sled Push", "Quads", "Sled", ["Glutes", "Calves"]],
    ["sled-pull", "Sled Pull", "Full Body", "Sled", ["Back", "Legs"]],
    ["battle-ropes", "Battle Ropes", "Conditioning", "Other", ["Shoulders", "Core"]],
    ["box-jump", "Box Jump", "Quads", "Bodyweight", ["Glutes", "Calves"]],
    ["burpee", "Burpee", "Full Body", "Bodyweight", ["Conditioning"]]
].map(([id, name, primaryMuscle, equipment, secondaryMuscles]) => ({
    id, name, primaryMuscle, equipment, secondaryMuscles
}));
